max_width = 120
group_imports = "StdExternalCrate"
imports_granularity = "Module"
wrap_comments = true
format_macro_matchers = true
reorder_impl_items = true
use_try_shorthand = true
use_field_init_shorthand = true
newline_style = "Unix"
